# Generated by Django 5.2.17 on 2026-09-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='max_salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
